matrix:
  include:
    - language: python
      python: 3.8
    - language: node_js
      node_js: 12

language: node_js
node_js:
  - "12"
cache:
  npm: true
  directories:
    - "node_modules"
    - "~/.cache"
before_script:
  - npm install
  - npm install -g remark-cli

script: npm test